// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {context} from '../models';

export function AddPlaylist(arg1:string):Promise<void>;

export function AddPlaylistItems(arg1:Array<data.PlaylistItemDto>):Promise<void>;

export function DeletePlaylist(arg1:string):Promise<void>;

export function DeletePlaylistItem(arg1:string):Promise<void>;

export function FFmpegPath():Promise<string>;

export function FFprobePath():Promise<string>;

export function GetCurrentPlaylist():Promise<data.PlaylistDto>;

export function GetPlaylist(arg1:string):Promise<data.PlaylistDto>;

export function GetPlaylistItemVideoMetadata(arg1:string,arg2:string,arg3:string):Promise<data.VideoMetadata>;

export function GetPlaylistName(arg1:string):Promise<string>;

export function GetPlaylists():Promise<Array<data.PlaylistListItem>>;

export function GetPreferences():Promise<data.AppConfig>;

export function GetStreamInfo(arg1:string):Promise<data.StreamInfo>;

export function InitNewPlaylistItems(arg1:Array<string>):Promise<Array<data.PlaylistItemDto>>;

export function OpenContainingFolder(arg1:string):Promise<void>;

export function RebalancePlaylistOrder(arg1:string):Promise<void>;

export function SavePreferences(arg1:Record<string, any>):Promise<void>;

export function SelectPlaylist(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdatePlaylist(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdatePlaylistItem(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdatePlaylistName(arg1:string,arg2:string):Promise<void>;
