// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlaylist(arg1) {
  return window['go']['internal']['PlayerService']['AddPlaylist'](arg1);
}

export function AddPlaylistItems(arg1) {
  return window['go']['internal']['PlayerService']['AddPlaylistItems'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['internal']['PlayerService']['DeletePlaylist'](arg1);
}

export function DeletePlaylistItem(arg1) {
  return window['go']['internal']['PlayerService']['DeletePlaylistItem'](arg1);
}

export function FFmpegPath() {
  return window['go']['internal']['PlayerService']['FFmpegPath']();
}

export function FFprobePath() {
  return window['go']['internal']['PlayerService']['FFprobePath']();
}

export function GetCurrentPlaylist() {
  return window['go']['internal']['PlayerService']['GetCurrentPlaylist']();
}

export function GetPlaylist(arg1) {
  return window['go']['internal']['PlayerService']['GetPlaylist'](arg1);
}

export function GetPlaylistItemVideoMetadata(arg1, arg2, arg3) {
  return window['go']['internal']['PlayerService']['GetPlaylistItemVideoMetadata'](arg1, arg2, arg3);
}

export function GetPlaylistName(arg1) {
  return window['go']['internal']['PlayerService']['GetPlaylistName'](arg1);
}

export function GetPlaylists() {
  return window['go']['internal']['PlayerService']['GetPlaylists']();
}

export function GetPreferences() {
  return window['go']['internal']['PlayerService']['GetPreferences']();
}

export function GetStreamInfo(arg1) {
  return window['go']['internal']['PlayerService']['GetStreamInfo'](arg1);
}

export function InitNewPlaylistItems(arg1) {
  return window['go']['internal']['PlayerService']['InitNewPlaylistItems'](arg1);
}

export function OpenContainingFolder(arg1) {
  return window['go']['internal']['PlayerService']['OpenContainingFolder'](arg1);
}

export function RebalancePlaylistOrder(arg1) {
  return window['go']['internal']['PlayerService']['RebalancePlaylistOrder'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['internal']['PlayerService']['SavePreferences'](arg1);
}

export function SelectPlaylist(arg1) {
  return window['go']['internal']['PlayerService']['SelectPlaylist'](arg1);
}

export function SetContext(arg1) {
  return window['go']['internal']['PlayerService']['SetContext'](arg1);
}

export function UpdatePlaylist(arg1, arg2) {
  return window['go']['internal']['PlayerService']['UpdatePlaylist'](arg1, arg2);
}

export function UpdatePlaylistItem(arg1, arg2) {
  return window['go']['internal']['PlayerService']['UpdatePlaylistItem'](arg1, arg2);
}

export function UpdatePlaylistName(arg1, arg2) {
  return window['go']['internal']['PlayerService']['UpdatePlaylistName'](arg1, arg2);
}
