// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {menu} from '../models';
import {plugin} from '../models';
import {data} from '../models';
import {logger} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CreateAppMenu():Promise<menu.Menu>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function ExecutePluginAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetLogLevel():Promise<string>;

export function GetPluginFile(arg1:string,arg2:string):Promise<string>;

export function GetPlugins():Promise<Array<plugin.PluginInfo>>;

export function GetReleaseYear():Promise<string>;

export function GetStreamURL(arg1:string):Promise<data.StreamURLResult>;

export function GetVideoServerPort():Promise<number>;

export function InstallPluginFromFile(arg1:string):Promise<plugin.PluginInfo>;

export function InstallPluginFromURL(arg1:string):Promise<plugin.PluginInfo>;

export function InstallUpdate(arg1:string):Promise<void>;

export function Logger():Promise<logger.Logger>;

export function PickDirectory():Promise<string>;

export function PickPluginFile():Promise<string>;

export function SetReadyToClose():Promise<void>;

export function StopHLSStream(arg1:string):Promise<void>;
