// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CreateAppMenu() {
  return window['go']['main']['App']['CreateAppMenu']();
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function ExecutePluginAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecutePluginAction'](arg1, arg2, arg3);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetPluginFile(arg1, arg2) {
  return window['go']['main']['App']['GetPluginFile'](arg1, arg2);
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetReleaseYear() {
  return window['go']['main']['App']['GetReleaseYear']();
}

export function GetStreamURL(arg1) {
  return window['go']['main']['App']['GetStreamURL'](arg1);
}

export function GetVideoServerPort() {
  return window['go']['main']['App']['GetVideoServerPort']();
}

export function InstallPluginFromFile(arg1) {
  return window['go']['main']['App']['InstallPluginFromFile'](arg1);
}

export function InstallPluginFromURL(arg1) {
  return window['go']['main']['App']['InstallPluginFromURL'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function Logger() {
  return window['go']['main']['App']['Logger']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickPluginFile() {
  return window['go']['main']['App']['PickPluginFile']();
}

export function StopHLSStream(arg1) {
  return window['go']['main']['App']['StopHLSStream'](arg1);
}
