// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAppMenu() {
  return window['go']['main']['App']['CreateAppMenu']();
}

export function GetVideoServerPort() {
  return window['go']['main']['App']['GetVideoServerPort']();
}
