// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';
import {plugin} from '../models';

export function CreateAppMenu():Promise<menu.Menu>;

export function ExecutePluginAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetPluginFile(arg1:string,arg2:string):Promise<string>;

export function GetPlugins():Promise<Array<plugin.PluginInfo>>;

export function GetVideoServerPort():Promise<number>;

export function InstallPluginFromFile(arg1:string):Promise<plugin.PluginInfo>;

export function InstallPluginFromURL(arg1:string):Promise<plugin.PluginInfo>;

export function PickDirectory():Promise<string>;

export function PickPluginFile():Promise<string>;
